### ISSUE TITLE
Per world speeds, cruiseSpeeds and cruiseSkipBlocks

### ISSUE THREAD

**Issue by eirikh1996** [TrollyLoki/Movecraft#10]
**Is your feature request related to a problem? Please describe.**
There should be added per world speeds, cruiseSpeeds and cruiseSkipBlocks

**Describe the solution you'd like**
Flags that would make a craft have different speed, cruiseSpeed and cruiseSkipBlocks in different worlds, where speed, cruiseSpeed and cruiseSkipBlocks act as default parameters if no such value is present.

Example:
```yaml
perWorldCruiseSkipBlocks:
   space: 100
   earth: 10
   mars: 30
```
